config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  resources :quiz_categories, only: [:index, :show]
  get '/quizzes/:id/play', to: 'quizzes#play', as: 'quiz_play'
  get '/quizzes/:id/play_mistakes', to: 'quizzes#play_mistakes', as: 'play_mistakes'
  resources :mistakes, only: [:index, :destroy] do
    collection do
      get :search
    end
  end
  resources :score_records, only: [:index, :show, :create]
  resources :talks, except: [:show] do
    collection do
      get :sort
      get :search
      get :tag_search
      get :feed
    end
    member do
      get :user
    end
  end
  resources :like_talks, only: [:create, :destroy]
  resources :comments
  resources :articles, only: [:show, :index] do
    collection do
      get :sort
      get :search
      get :tag_search
    end
  end
  resources :like_articles, only: [:create, :destroy]
  resources :bookmarks, only: [:index, :create, :destroy]
  resources :communities do
    collection do
      get :sort
      get :search
      get :tag_search
      get :joined
    end
    member do
      get :join
      get :leave
    end
  end
  resources :community_users, only: [:create, :destroy]
  resources :announcements, only: [:index, :show]
  resources :events, only: [:index, :show]
  resources :reviews, only: [:index, :destroy]

  namespace :admin do
    get '/', to: 'static_pages#home'
    resources :users, only: [:index, :show, :destroy] do
      collection do
        get :search
      end
    end
    resources :quizzes do
      collection do
        get :all
        get :search
      end
      member do
        get :all_in_level
        get :all_in_section
        get :titles
        get :quizzes_in_title
      end
    end
    get '/quizzes/section_list/:id/:page', to: 'quizzes#get_section_list', as: 'quiz_sections'
    get '/quizzes/title_list/:id/:page', to: 'quizzes#get_title_list', as: 'quiz_titles'
    post 'category_with_experience_forms', to: 'quiz_categories#create'
    resources :quiz_categories do
      collection do
        get :levels
        get :new_level
        get :new_quiz
        get :search
      end
      member do
        get :new_category
        get :categories
        patch :sort
        get :edit_quiz
        get :new_quiz
      end
    end
    resources :articles do
      collection do
        get :search
        get :tag_search
        post :upload_image
        post :delete_image
      end
    end
    resources :communities do
      collection do
        get :search
        get :tag_search
      end
    end
    resources :talks, only: [:index, :show, :destroy] do
      collection do
        get :search
        get :comments
      end
    end
    resources :comments, only: [:index, :show, :destroy] do
      collection do
        get :search
      end
    end
    resources :announcements do
      collection do
        get :search
        get :tag_search
      end
    end
    resources :events do
      collection do
        get :search
        get :calendar
      end
    end
    resource :user, only: [:index, :destroy]
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
  }

  # deviseのroutesをカスタマイズで追加する
  devise_scope :user do
    get '/ranking', to: 'users#index', as: 'ranking'
    get 'user/:id', to: 'users#show', as: 'user'
    get '/user/:id/edit', to: 'users/registrations#edit', as: 'edit_profile'
  end

  # devise/~~~ をadmins/~~~に変える
  #   devise_for :admins, controllers: {
  #   sessions:      'admins/sessions',
  #   passwords:     'admins/passwords',
  #   registrations: 'admins/registrations'
  # }

  # routesをカスタマイズして、追加する
  # devise_for :admins, only: [:session] do
  # get '/admins/sign_in', :to => 'admins/sessions#new', :as => :new_admin_session
  # post 'admins/sign_in', :to =>'admins/sessions#create',:as => :admin_session
  # delete '/admins/', :to => 'admins/sessions#destroy', :as => :destroy_admin_session
  # end

  devise_for :admin, skip: :all
  devise_scope :admin do
    # loginリクエストに対してadmins/sessionsコントローラのnewアクションにルーティングし、new_user_session_pathと名付ける
    get '/admin/sign_in' => 'admin/sessions#new', as: 'new_admin_session'
    post '/admin/sign_in' => 'admin/sessions#create', as: 'admin_session'
    delete '/admin/sign_out' => 'admin/sessions#destroy', as: 'destroy_admin_session'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  acts_as_taggable
  is_impressionable counter_cache: true
  enum status: { draft: false, published: true }
  has_many :bookmarks, dependent: :destroy
  has_many :users, through: :bookmarks
  has_many :like_articles, dependent: :destroy
  has_many :users, through: :like_articles
  has_one_attached :img
  validate :img_presence
  validate :image_content_type, if: :was_attached?
  validates :status, :title, :contents, :lead, :status, presence: true
  validates :title, length: (1..100)
  validates :lead, length: (1..240)
  validates :contents, length: (1..200000)
  validates :status, inclusion: { in: ["published", "draft"] }
  scope :bookmarks, -> (user) do
    includes(:bookmarks).where("bookmarks.user_id = user.id").order("bookmarks.created_at Desc")
  end
  scope :viewed_top_3, -> { where(status: true).with_attached_img.order(impressions_count: :desc).limit(3) }
  scope :bookmarked_top_3, -> { where(status: true).with_attached_img.order(bookmarks_count: :desc).limit(3) }
  scope :liked_top_3, -> { where(status: true).with_attached_img.order(likes_count: :desc).limit(3) }
  scope :published, -> { where(status: "published").order(id: "DESC") }
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_action :authenticate_admin!, only: [:index, :new, :create, :edit, :update, :destroy]
  before_action :set_article_tags, only: [:index, :search, :tag_search]
  before_action :set_available_tags_to_gon, only: [:new, :edit, :confirm]

  def index
    @q = Article.ransack(params[:q])
    @articles = @q.result(distinct: true).paginate(params[:page], 15)
  end

  def show
    @article = Article.find(params[:id])
    @tags = @article.tags_on(:tags)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash.now[:notice] = 'article was saved successfully'
      redirect_to admin_articles_path
    else
      flash.now[:notice] = 'failed to save article .Try again'
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
    gon.article_tags = @article.tag_list
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    if @article.save
      @article.img.purge if article_params[:delete_img].present?
      flash.now[:notice] = 'article was updated successfully'
      redirect_to admin_articles_path
    else
      flash.now[:notice] = 'failed to update article...'
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    respond_to do |format|
      format.html { redirect_to admin_articles_path }
      format.js { render :action => "destroy" }
    end
  end

  def bookmark_articles
    Article.
      includes(:bookmarks).
      references.call(:bookmarks).
      where("bookmark.id", current_user.id).
      paginate(params[15]).sorted
  end

  def upload_image
    image_uploader = Article::ImageUploader.new(params[:upload_image])
    if image_uploader.upload_image
      object = image_uploader.get_bucket.object(image_uploader.get_key_name)
      url = object.public_url.sub!(/.ap/, "-ap")
      render json: { url: URI.parse(url) }
    else
      head 400
    end
  end

  def delete_image
    image_delete = Article::DeleteImage.new(params[:image_url])
    if image_delete.delete
      puts "deleted the image successfully"
    else
      head 400
    end
  end

  def search
    is_pagination?(params)
    if !params[:q]['title_or_lead_cont_any'].nil?
      params[:q]['title_or_lead_cont_any'] = params[:q]['title_or_lead_cont_any'].split(/[ ]/)
      @keywords = Article.ransack(params[:q])
      @articles = @keywords.result.paginate(params[:page], 15)
      @q = Article.ransack(params[:q])
    else
      @q = Article.ransack(params[:q])
      @articles = @q.result(distinct: true).paginate(params[:page], 15)
    end
    render template: 'admin/articles/index'
  end

  def tag_search
    @articles = Article.tagged_with(params[:tag]).paginate(params[:page], 15)
    @q = Article.ransack(params[:q])
    render template: 'admin/articles/index'
  end

  private

  def article_params
    params.require(:article).permit(:title, :lead, :tag_list, :img, :delete_img, :contents, :status)
  end

  def set_available_tags_to_gon
    gon.available_tags = Article.tags_on(:tags).pluck(:name)
  end

  def set_article_tags
    @tags = Article.all_tags
  end

  def is_pagination?(params)
    if params[:q]['title_or_lead_cont_any'].is_a?(Array)
      params[:q]['title_or_lead_cont_any'] = params[:q]['title_or_lead_cont_any'].join(" ")
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :only_login_user!
  before_action :get_unchecked_announce_count, :get_not_done_reviews_count
  before_action :set_article_tags, only: [:index, :search, :tag_search]
  before_action :set_ranked_articles, only: [:show, :index, :search, :tag_search]
  impressionist :actions => [:show]

  def index
    @q = Article.published.with_attached_img.ransack(params[:q])
    @articles = @q.result(distinct: true).paginate(params[:page], 15)
  end

  def show
    if @article = Article.find_by_id(params[:id])
      @tags = @article.tags_on(:tags)
      @q = Article.with_attached_img.ransack(params[:q])
    else
      redirect_to articles_path, flash: { alert: "coundn't find an article ...." }
    end
  end

  def tag_search
    @articles = Article.with_attached_img.tagged_with(params[:tag]).sorted
    @q = Article.ransack(params[:q])
    render template: 'articles/index'
  end

  def search
    if !params[:q].nil?
      params[:q]['title_or_lead_cont_any'] = params[:q]['title_or_lead_cont_any'].split(/[ ]/)
      @keywords = Article.with_attached_img.ransack(params[:q])
      @articles = @keywords.result.sorted
      @q = Article.ransack(params[:q])
    else
      @q = Article.ransack(params[:q])
      @articles = @q.result(distinct: true).sorted
    end
    render template: 'articles/index'
  end

  private

  def set_article_tags
    @tags = Article.all_tags
  end

  def set_ranked_articles
    @viewed_top_3 = Article.viewed_top_3
    @bookmarked_top_3 = Article.bookmarked_top_3
    @liked_top_3 = Article.liked_top_3
  end
end

app/views/articles/_action_btns.html.erb
<span id="like_btn_<%= article.id %>">
  <%= render partial: 'articles/like_btn' , locals: { article: article } %>
</span>
<% if user_signed_in? %>
  <span id="bookmark_btn_<%= article.id %>">
    <%= render partial: 'articles/bookmark_btn' , locals: { article: article } %>
  </span>
<% end %>

app/views/articles/_article.html.erb
<%= link_to article_path(article), class: "article_link_#{article.id}" do %>
  <div class="article" id="article_<%= article.id %>">
    <%= render "article_img", article: article %>
    <div class="article_headline_wrapper inline">
      <p class="article_title bold"><%= article.title %></p>
      <p class="article_lead"><%= article.lead %></p>
      <p class="article_data right">
        <span class="posted_day"><%= render partial: "posted_day", locals: { article: article } %></span>
        <span class="like_btn"><%= icon("fas", "heart") %> <%= article.likes_count %></span>
        <span class="bookmark_btn"><%= icon("fas", "star") %> <%= article.bookmarks_count %></span>
        <span class="view_count"><%= icon("fas", "eye") %> <%= article.impressions_count %></span>
      </p>
    </div>
  </div>
<% end %>

app/views/articles/_article_img.html.erb
<div class="article_img_wrapper">
  <% if article.img.attached? %>
    <p><%= image_tag article.img, class:"thumbnail_img" %></p>
  <% else %>
    <div class="inline thumbnail_panel <%= thumbnails_color(article) %>">
      <p>Japanepa</p>
    </div>
  <% end %>
</div>

app/views/articles/_bookmark_btn.html.erb
<% if current_user.already_bookmark?(article) %>
  <%= link_to bookmark_path(article), class: "bookmark_btn" ,remote: true, method: :delete do %>
    <%= icon("fas", "star") %> <%= article.bookmarks.count %>
  <% end %>
<% else %>
  <%= link_to bookmarks_path(id: article.id), class: "bookmark_btn", remote: true, method: :post do %>
    <%= icon("far", "star") %> <%= article.bookmarks.count %>
  <% end %>
<% end %>

app/views/articles/_form_summernote.erb
<%= form_with model: @article, local: true, builder: CustomFormBuilder do |f| %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field" >
    <%= f.label :lead %><br>
    <%= f.text_area :lead %>
  </div>
  <div class="field">
    <p>Top-Image</p>
    <div class="post_img_area">
    <%= f.file_field :img, id: 'post_img' %>
    <% if @article.img? %>
      <%= image_tag @article.img.to_s, class: 'present_topImg' %>
      <label><%= f.check_box :remove_img %> 画像を削除</label>
    <% else %>
      <%= f.hidden_field :img_cache %>
    <% end %>
    <img id="postImg_prev" src="#" class='hidden' />
    </div>
  </div>
  <div class="field">
    <%= f.label :contents %>
    <%= f.text_area :contents, 'data-provider': :summernote %>
  </div>
  <div class="actions">
    <%= f.submit "submit" %>
  </div>
<% end %>

app/views/articles/_like_btn.html.erb
<% if current_user.already_liked_article?(article) %>
  <%= link_to like_article_path(article), class: "like_btn", remote: true, method: :delete do %>
    <%= icon("fas", "heart") %> <%= article.like_articles.count %>
  <% end %>
<% else %>
  <%= link_to like_articles_path(id: article.id), class: "like_btn", remote: true, method: :post do %>
    <%= icon("far", "heart") %> <%= article.like_articles.count %>
  <% end %>
<% end %>

app/views/articles/_posted_day.html.erb
<span class="posted_day">
  <% if updated?(article) %>
    <%= icon("fas", "sync-alt") %> <%= article.updated_at.strftime('%Y/%m/%d') %>
  <% else %>
    <%= icon("fas", "clock") %> <%= article.created_at.strftime('%Y/%m/%d') %>
  <% end %>
</span>

app/views/articles/_ranked_article.html.erb
<%= link_to article_path(article) do %>
  <div class="inner_article">
    <p class="rank_number center bold <%= top_3(article_counter) %>">
      <span><%= article_counter + 1 %></span>
    </p>
    <%= render "article_img", article: article %>
    <div class="inner_article_headline_wrapper">
      <p class="inner_article_title bold"><%= article.title %></p>
      <p class="sp inner_article_lead"><%= article.lead %></p>
      <p class="article_data right">
        <span class="like_btn"><%= icon("fas", "heart") %> <%= article.likes_count %></span>
        <span class="bookmark_btn"><%= icon("fas", "star") %> <%= article.bookmarks_count %></span>
        <span class="view_count"><%= icon("fas", "eye") %> <%= article.impressions_count %></span>
      </p>
    </div>
  </div>
<% end %>

app/views/articles/_side_section.html.erb
<div class="side_content">
  <h4><%= icon("fas", "search") %> Search(けんさく)</h4>
  <%= search_form_for @q, url: search_articles_path, class: "search_form" do |f| %>
    <%= f.text_field :title_or_lead_cont_any, class: "search_input" %>
    <%= f.button :type => "submit", class: "search_btn" do %>
      <%= icon("fas", "search") %>
    <% end %>
  <% end %>
</div>
<div class="side_content">
  <h4><%= icon("fas", "tags") %> Tags(タグ)</h4>
  <ul class="tags">
    <% if @tags.present? %>
      <%= render partial: 'tag', collection: @tags, as: :tag %>
    <% else %>
    <li>No tags....</li>
    <% end %>
  </ul>
</div>
<%= render 'top_3_articles' %>

app/views/articles/_tag.html.erb
<li><%= link_to tag.name, tag_search_articles_path(tag: tag.name) %></li>

app/views/articles/_top_3_articles.html.erb
<div class="side_content">
  <h4><%= icon("far", "eye") %> Most Viewed</h4>
  <ul class="inner_article_content top_3_content">
    <% if @viewed_top_3.present? %>
      <%= render partial: "articles/ranked_article", collection: @viewed_top_3, as: :article %>
    <% else %>
      <li>No Data</li>
    <% end %>
  </ul>
</div>
<div class="side_content">
  <h4><%= icon("fas", "star") %> Most Bookmark</h4>
  <ul class="inner_article_content top_3_content">
    <% if @bookmarked_top_3.present? %>
      <%= render partial: "articles/ranked_article", collection: @bookmarked_top_3, as: :article %>
    <% else %>
      <li>No Data</li>
    <% end %>
  </ul>
</div>
<div class="side_content">
  <h4><%= icon("fas", "heart") %> Most Liked</h4>
  <ul class="inner_article_content top_3_content">
    <% if @liked_top_3.present? %>
      <%= render partial: "articles/ranked_article", collection: @liked_top_3, as: :article %>
    <% else %>
      <li>No Data</li>
    <% end %>
  </ul>
</div>

app/views/articles/index.html.erb
<% content_for(:html_title) { "Articles Index" } %>
<% breadcrumb :articles, @articles %>
<div class="section_wrapper">
  <div class="main_section">
    <h1 class="center bold page_title">Articles index</h1>
    <div class="article_index jscroll">
      <% if @articles.present? %>
        <%= render partial: 'article', collection: @articles, as: :article %>
      <% else %>
        <p class="center">No article...</p>
      <% end %>
    </div>
  </div>
  <div class="side_section article_page pc">
    <%= render 'side_section' %>
  </div>
</div>
<div class="user_menu_in_mobile hidden">
  <%= render "user_menu_in_mobile" %>
  <%= render "side_section" %>
</div>
<%= render "back_to_top_btn" %>

app/views/articles/index.js.erb
$("#article_index").append("<%= j(render partial: 'article', collection: @articles, as: :article) %>");
$("#see_more").html("<%= escape_javascript(link_to_next_page(@articles, '↓ scroll ↓', remote: true)) %>");

app/views/articles/show.html.erb
<% content_for(:html_title) { "Article-#{@article.title}" } %>
<% breadcrumb :show_article, @article %>
<div class="section_wrapper">
  <div class="main_section">
    <div class="article_wrapper">
      <p class="posted_time">
        <%= render partial: 'posted_day', locals: { article: @article } %>
        <%= render partial: "action_btns", locals: { article: @article } %>
      </p>
      <p class="article_title"><%= @article.title %></p>
      <%= render "article_img", article: @article %>
      <hr>
      <div class="article_contents" id="contents">
        <%= raw(@article.contents) %>
      </div>
    </div>
  </div>
  <div class="side_section article_page pc">
    <%= render 'side_section' %>
  </div>
  <div class="user_menu_in_mobile hidden">
    <%= render "user_menu_in_mobile" %>
    <%= render "side_section" %>
  </div>
</div>
<%= render "back_to_top_btn" %>