config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  resources :quiz_categories, only: [:index, :show]
  get '/quizzes/:id/play', to: 'quizzes#play', as: 'quiz_play'
  get '/quizzes/:id/play_mistakes', to: 'quizzes#play_mistakes', as: 'play_mistakes'
  resources :mistakes, only: [:index, :destroy] do
    collection do
      get :search
    end
  end
  resources :score_records, only: [:index, :show, :create]
  resources :talks, except: [:show] do
    collection do
      get :sort
      get :search
      get :tag_search
      get :feed
    end
    member do
      get :user
    end
  end
  resources :like_talks, only: [:create, :destroy]
  resources :comments
  resources :articles, only: [:show, :index] do
    collection do
      get :sort
      get :search
      get :tag_search
    end
  end
  resources :like_articles, only: [:create, :destroy]
  resources :bookmarks, only: [:index, :create, :destroy]
  resources :communities do
    collection do
      get :sort
      get :search
      get :tag_search
      get :joined
    end
    member do
      get :join
      get :leave
    end
  end
  resources :community_users, only: [:create, :destroy]
  resources :announcements, only: [:index, :show]
  resources :events, only: [:index, :show]
  resources :reviews, only: [:index, :destroy]

  namespace :admin do
    get '/', to: 'static_pages#home'
    resources :users, only: [:index, :show, :destroy] do
      collection do
        get :search
      end
    end
    resources :quizzes do
      collection do
        get :all
        get :search
      end
      member do
        get :all_in_level
        get :all_in_section
        get :titles
        get :quizzes_in_title
      end
    end
    get '/quizzes/section_list/:id/:page', to: 'quizzes#get_section_list', as: 'quiz_sections'
    get '/quizzes/title_list/:id/:page', to: 'quizzes#get_title_list', as: 'quiz_titles'
    post 'category_with_experience_forms', to: 'quiz_categories#create'
    resources :quiz_categories do
      collection do
        get :levels
        get :new_level
        get :new_quiz
        get :search
      end
      member do
        get :new_category
        get :categories
        patch :sort
        get :edit_quiz
        get :new_quiz
      end
    end
    resources :articles do
      collection do
        get :search
        get :tag_search
        post :upload_image
        post :delete_image
      end
    end
    resources :communities do
      collection do
        get :search
        get :tag_search
      end
    end
    resources :talks, only: [:index, :show, :destroy] do
      collection do
        get :search
        get :comments
      end
    end
    resources :comments, only: [:index, :show, :destroy] do
      collection do
        get :search
      end
    end
    resources :announcements do
      collection do
        get :search
        get :tag_search
      end
    end
    resources :events do
      collection do
        get :search
        get :calendar
      end
    end
    resource :user, only: [:index, :destroy]
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
  }

  # deviseのroutesをカスタマイズで追加する
  devise_scope :user do
    get '/ranking', to: 'users#index', as: 'ranking'
    get 'user/:id', to: 'users#show', as: 'user'
    get '/user/:id/edit', to: 'users/registrations#edit', as: 'edit_profile'
  end

  # devise/~~~ をadmins/~~~に変える
  #   devise_for :admins, controllers: {
  #   sessions:      'admins/sessions',
  #   passwords:     'admins/passwords',
  #   registrations: 'admins/registrations'
  # }

  # routesをカスタマイズして、追加する
  # devise_for :admins, only: [:session] do
  # get '/admins/sign_in', :to => 'admins/sessions#new', :as => :new_admin_session
  # post 'admins/sign_in', :to =>'admins/sessions#create',:as => :admin_session
  # delete '/admins/', :to => 'admins/sessions#destroy', :as => :destroy_admin_session
  # end

  devise_for :admin, skip: :all
  devise_scope :admin do
    # loginリクエストに対してadmins/sessionsコントローラのnewアクションにルーティングし、new_user_session_pathと名付ける
    get '/admin/sign_in' => 'admin/sessions#new', as: 'new_admin_session'
    post '/admin/sign_in' => 'admin/sessions#create', as: 'admin_session'
    delete '/admin/sign_out' => 'admin/sessions#destroy', as: 'destroy_admin_session'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/quizzes_controller.rb
class Admin::QuizzesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_level_options, only: [:index, :search]

  def index
    @q = Quiz.includes(:category).ransack(params[:q])
    @quizzes = @q.result(distinct: true).paginate(params[:page], 15)
  end

  def new
    @quiz = Quiz.new
    @options = get_levels("new")
  end

  def create
    @quiz = Quiz.new(quiz_params)
    if from_category_page?(request)
      create_in_category_page(@quiz)
    else
      if @quiz.save
        flash.now[:notice] = "registered successfully"
        redirect_to admin_quizzes_path
      else
        @options = get_levels("index")
        @options.unshift({ name: "All", value: 0, path: all_admin_quizzes_path })
        render "admin/quizzes/new"
      end
    end
  end

  def edit
    @quiz = Quiz.find(params[:id])
  end

  def update
    @quiz = Quiz.find(params[:id])
    @quiz.update(quiz_params)
    if from_category_page?(request)
      create_in_category_page(@quiz)
    else
      if @quiz.save
        flash.now[:notice] = "updated successfully"
        redirect_to admin_quizzes_path
      else
        render 'edit'
      end
    end
  end

  def destroy
    Quiz.find(params[:id]).destroy
    if from_category_page?(request)
      flash.now[:notice] = "edited quiz successfully!"
      redirect_to admin_quiz_category_path(quiz.category_id)
    else
      flash.now[:notice] = "edited quiz successfully!"
      redirect_to admin_quizzes_path
    end
  end

  def search
    is_pagination?(params)
    if !params[:q]['question_or_choice1_cont_any'].nil?
      params[:q]['question_or_choice1_cont_any'] = params[:q]['question_or_choice1_cont_any'].split(/[ ]/)
      @keywords = Quiz.ransack(params[:q])
      @quizzes = @keywords.result.paginate(params[:page], 15)
      @q = Quiz.ransack(params[:q])
    else
      @q = Quiz.ransack(params[:q])
      @quizzes = @q.result(distinct: true).paginate(params[:page], 15)
    end
    render template: 'admin/quizzes/index'
  end

  def all_in_level
    level = QuizCategory.find(params[:id])
    all_title_in_level = level.leaves
    @q = Quiz.where(category_id: all_title_in_level).ransack(params[:q])
    @quizzes = @q.result(distinct: true).paginate(params[:page], 15)
    render 'narrow_down'
  end

  def all_in_section
    section = QuizCategory.find(params[:id])
    all_title_in_section = section.leaves
    @q = Quiz.where(category_id: all_title_in_section).ransack(params[:q])
    @quizzes = @q.result(distinct: true).paginate(params[:page], 15)
    render 'narrow_down'
  end

  def quizzes_in_title
    @q = Quiz.get_quizzes_in(params[:id].to_i).ransack(params[:q])
    @quizzes = @q.result(distinct: true)
    render 'narrow_down'
  end

  def get_section_list
    @level = QuizCategory.find(params[:id])
    current_page = params[:page]
    @options = get_sections(@level, current_page)
    # all_quizzes_in_level_path = "/all_quizzes_in_level/" + params[:id] + "/" + params[:page]
    add_options(current_page, @options, all_in_level_admin_quiz_path)
    render json: @options
  end

  def get_title_list
    @section = QuizCategory.find(params[:id])
    current_page = params[:page]
    @options = get_titles(@section, current_page)
    # get_all_quizzes_in_section_path = "/all_quizzes_in_section/" + params[:id] + "/" + current_page
    add_options(current_page, @options, all_in_section_admin_quiz_path)
    render json: @options
  end

  private

  def quiz_params
    question = ''
    extract_inner_text(params[:quiz][:question_html], question)
    params.require(:quiz).
      permit(:category_id, :question_html, :choice1, :choice2, :choice3, :choice4).
      merge(question: question)
  end

  def search_params
    params.require(:q).permit(:question_cont)
  end

  def extract_inner_text(html, question)
    q = html
    charset = nil
    doc = Nokogiri::HTML.parse(q, nil, charset)
    doc.css('p').each do |f|
      question << f.content
    end
  end

  def set_level_options
    @options = get_levels("index")
  end

  def get_levels(page)
    levels = QuizCategory.where(depth: 0)
    levels.map do |level|
      { name: level.name, value: level.id, path: admin_quiz_sections_path(id: level.id, page: page) }
    end
  end

  def get_sections(level, page)
    QuizCategory.sections_in(level).map do |section|
      { name: section.name, value: section.id, path: admin_quiz_titles_path(section, page) }
    end
  end

  def get_titles(section, page)
    QuizCategory.titles_in(section).map do |title|
      { name: title.name, value: title.id, path: quizzes_in_title_admin_quiz_path(title) }
    end
  end

  def add_options(page, valiable, path)
    if valiable.any?
      if page == "index"
        valiable.unshift({ name: "all", value: 0, path: path })
      end
      valiable.unshift({ name: "選択してください", value: '', path: '' })
    else
      valiable.unshift({ name: "なし", value: '', path: '' })
    end
  end

  def from_category_page?(request)
    request.referer&.include?("quiz_categories")
  end

  def create_in_category_page(quiz)
    if quiz.save!
      @quizzes = Quiz.where(category_id: quiz.category_id)
      flash.now[:notice] = "新しいクイズを作成しました！"
      render 'admin/quiz_categories/create_quiz'
    else
      @category = QuizCategory.find(quiz.category_id)
      render "admin/quiz_categories/new_quiz"
    end
  end

  def is_pagination?(params)
    if params[:q]['question_or_choice1_cont_any'].is_a?(Array)
      params[:q]['question_or_choice1_cont_any'] = params[:q]['question_or_choice1_cont_any'].join(" ")
    end
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  include QuizzesHelper
  before_action :only_login_user!
  before_action :get_unchecked_announce_count, :get_not_done_reviews_count

  def play
    @category = QuizCategory.find(params[:id])
    # title表示のため
    @quizzes = Quiz.where(category_id: params[:id])
    set_quizzes(@categroy)
  end

  def play_mistakes
    @category = QuizCategory.find(params[:id])
    if mistake_ids == current_user.mistakes.where(title_id: @category.id).pluck(:quiz_id)
      @quizzes = Quiz.where(id: mistake_ids)
      set_quizzes(@categroy)
      render :play
    else
      @levels = QuizCategory.includes(categories: :quizzes).levels
      render :index
      flash[:alert] = "there is no mistake record"
    end
  end

  def sections
    @level = QuizCategory.find(params[:id])
    @sections = sections_in(@level)
  end

  def titles
    @sections = QuizCategroy.find(params[:id])
    @titles = titles_in(@section)
  end

  private

  def set_quizzes(category)
    gon.quizTitle = @category.name
    gon.title_id = @category.id
    gon.quizSet = []
    @quizzes.each do |quiz|
      gon.quizSet.push(
        id: "#{quiz.id}",
        question: "#{quiz.question_html}",
        choices: ["#{quiz.choice1}", "#{quiz.choice2}", "#{quiz.choice3}", "#{quiz.choice4}"]
      )
    end
  end
end

app/views/admin/quizzes/_category_search.html.erb
<p class="category_sort_btn bold sp">
  カテゴリーで絞り込む
  <span class="open_accordion">▼</span>
  <span class="close_accordion hidden">▲</span>
</p>
<div class="category_sort pc">
  <p class="bold pc">・カテゴリーで絞り込む</p>
  <div>
    <label>Level</label>
    <select id="select_level" class="index">
      <option>選択してください</option>
      <%= render partial: 'option', collection: @options, as: :option %>
    </select>
  </div>
  <div>
    <label>Section</label>
    <select id="select_section">
      <option>---</option>
    </select>
  </div>
  <div>
    <label>Title</label>
    <select id="select_title" class="index_page">
      <option>---</option>
    </select>
  </div>
</div>

app/views/admin/quizzes/_columns.html.erb
<tr class="index_head">
  <th><%= sort_link(@q, :id, "No.", default_order: :desc, anchor: "index") %></th>
  <th><%= sort_link(@q, :question, "Question", default_order: :desc, anchor: "index") %></th>
  <th><%= sort_link(@q, :choice1, "Answer", default_order: :desc, anchor: "index") %></th>
  <th><%= sort_link(@q, :choice2, "C2", default_order: :desc, anchor: "index") %></th>
  <th><%= sort_link(@q, :choice3, "C3", default_order: :desc, anchor: "index")%></th>
  <th><%= sort_link(@q, :choice4, "C4", default_order: :desc, anchor: "index") %></th>
  <th class="date_column"><%= sort_link(@q, :created_at, "Creation Date", default_order: :desc, anchor: "index") %></th>
  <th class="date_column"><%= sort_link(@q, :updated_at, "Update Date", default_order: :desc, anchor: "index") %></th>
  <th class="action_column notes">※ソート可<br>（カラム名をクリック）</th>
</tr>

app/views/admin/quizzes/_form.html.erb
<div class="quiz_form_wrapper">
  <%= form_with model: [:admin, quiz], local:true, builder: CustomFormBuilder do |f| %>
    <p class="error_message"><%="入力値が正しくありません。" if quiz.errors.any? %></p>
    <% unless quiz.category_id.nil? %>
      <%= f.hidden_field :category_id, value: quiz.category_id %>
    <% else %>
      <div class="field">
        <%= f.label :category_id %>
        <%= f.select :category_id, [], { include_blank: true }, id: 'select_title', class: 'form_page' %>
      </div>
    <% end %>
    <div class="field">
      <%= f.label :question %>
      <%= f.text_area :question_html, class: 'question_input', 'data-provider': :summernote %>
    </div>
    <div class="field">
      <%= f.label :choice1 %>
      <%= f.text_field :choice1 %>
    </div>
    <div class="field">
      <%= f.label :choice2%>
      <%= f.text_field :choice2 %>
    </div>
    <div class="field">
      <%= f.label :choice3 %>
      <%= f.text_field :choice3 %>
    </div>
    <div class="field">
      <%= f.label :choice4 %>
      <%= f.text_field :choice4 %>
    </div>
    <div class="actions">
      <%= f.submit  form_btn, data: { confirm: "送信しますか？"} %>
    </div>
  <% end %>
  </div>
<%= javascript_include_tag 'summernote' %>

app/views/admin/quizzes/_option.html.erb
<option value = <%= option[:value] %> , get-select-list-path =<%= option[:path] %>>
  <%= option[:name] %>
</option>

app/views/admin/quizzes/_quiz.html.erb
<tr class="index_content row_<%= quiz_counter %>" id="quiz_<%= quiz.id %>">
  <td><%= quiz.id %></td>
  <td class="truncate_column"><%= quiz.question.truncate(20) %></td>
  <td><%= quiz.choice1.truncate(20) %></td>
  <td><%= quiz.choice2.truncate(20) %></td>
  <td><%= quiz.choice3.truncate(20) %></td>
  <td><%= quiz.choice4.truncate(20) %></td>
  <td class="date_column"><%= quiz.updated_at.strftime('%Y/%m/%d') %></td>
  <td class="date_column"><%= quiz.created_at.strftime('%Y/%m/%d') %></td>
  <td class="action_column">
    <%= link_to edit_admin_quiz_path(quiz), class: "edit_btn inline" do %>
      <%= icon("fas", "edit") %> 編集
    <% end %>
    <%= link_to admin_quiz_path(quiz), class: "delete_btn inline",data: { confirm: 'このユーザーを削除しますか?' } ,method: :delete do %>
      <%= icon("fas", "trash-alt") %> 削除
    <% end %>
  </td>
</tr>

app/views/admin/quizzes/choice_page.html.erb
<% content_for(:html_title) { "Quiz Index" } %>
<% breadcrumb :admin_quizzes, @quizzes %>
<div class="choice_wrapper center">
  <h1>Choose index page<h1>
    <%= link_to admin_quizzes_path, id: 'quiz_page_panel' do %>
      <p class="inline">Quizzes</p>
    <% end %>
    <%= link_to admin_quiz_categories_path, id: 'category_page_panel' do %>
      <p class="inline">Categories</p>
    <% end %>
</div>

app/views/admin/quizzes/create.js.erb
$('#quiz_<%= @quiz.id %>').html("<%= j(render partial: 'quiz_content', locals: { quiz: @quiz }) %>");
$('#modal').empty();
$('#modalArea').fadeOut();

app/views/admin/quizzes/destroy.js.erb
$("#quiz_<%= @quiz.id %>").remove();

app/views/admin/quizzes/edit.html.erb
<% content_for(:html_title) { "Edit Quiz-#{@quiz.question}" } %>
<% breadcrumb :edit_quiz, @quiz %>
<p class="admin_form_title">Edit Quiz</p> 
<div class="form_wrapper">
  <p class="right">
  <%= link_to admin_quiz_path(@quiz), class: "delete_btn inline", data: { confirm: 'このクイズを削除しますか?' }, method: :delete do %>
    <%= icon("fas", "trash-alt") %> 削除
  <% end %>
  </p>
  <%= render partial: 'form', locals: { quiz: @quiz, form_btn: "編集" } %> 
</div>

app/views/admin/quizzes/edit_form.js.erb
$("#modal").empty();
$("#modal").html("<%= j(render partial: 'admin/quizzes/form', locals: { quiz: @quiz, category: @category }) %>");
$('#modalArea').fadeIn();

app/views/admin/quizzes/get_section_list.js.erb
$("＃select_section").html("<%= j(render partial: 'option', collection: @options, as: :option) %>");

app/views/admin/quizzes/narrow_down.js.erb
$(".quizzes_list").html("<%= j(render partial: 'quiz', collection: @quizzes, as: :quiz) %>");

app/views/admin/quizzes/quiz_title_index.html.erb
<h1> Quiz section index </h1>
<% if admin_signed_in? %>
  <div class="col-xs-12">
    <div>
      <div class="col-xs-12 col-lg-4 ">
        <div class=" card redBtn link">
        <h1>Create New Quiz</h1>
        <%= link_to "",new_quiz_path %>
        </div>
      </div>
    </div>
  </div>
<% end %>
<div class="row">
  <% @n5_quiz.each do |section,quizTitles| %>
    <div class="col-xs-12">
      <h1>●<%= section %></h1> 
      <div>
        <% quizTitles.each do |quizTitle| %>
        <div class="col-xs-12 col-lg-4 ">
          <div class=" card redBtn link">
          <h1><%= quizTitle %></h1>
          <% if admin_signed_in? %>
            <%= link_to "",controller:"quizzes",action:"edit_quiz_index",title:quizTitle %>
          <% else %>
            <%= link_to "",controller:"quizzes",action:"show",title:quizTitle %>
            <% end %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/quizzes/update.js.erb
$('#quiz_<%= @quiz.id %>').html("<%= j(render partial: 'quiz_content', locals: { quiz: @quiz }) %>");
$('#modal').empty();
$('#modalArea').fadeOut();
$("#flash_wrapper").html("<%= j(render 'layouts/flash') %>");