config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  resources :quiz_categories, only: [:index, :show]
  get '/quizzes/:id/play', to: 'quizzes#play', as: 'quiz_play'
  get '/quizzes/:id/play_mistakes', to: 'quizzes#play_mistakes', as: 'play_mistakes'
  resources :mistakes, only: [:index, :destroy] do
    collection do
      get :search
    end
  end
  resources :score_records, only: [:index, :show, :create]
  resources :talks, except: [:show] do
    collection do
      get :sort
      get :search
      get :tag_search
      get :feed
    end
    member do
      get :user
    end
  end
  resources :like_talks, only: [:create, :destroy]
  resources :comments
  resources :articles, only: [:show, :index] do
    collection do
      get :sort
      get :search
      get :tag_search
    end
  end
  resources :like_articles, only: [:create, :destroy]
  resources :bookmarks, only: [:index, :create, :destroy]
  resources :communities do
    collection do
      get :sort
      get :search
      get :tag_search
      get :joined
    end
    member do
      get :join
      get :leave
    end
  end
  resources :community_users, only: [:create, :destroy]
  resources :announcements, only: [:index, :show]
  resources :events, only: [:index, :show]
  resources :reviews, only: [:index, :destroy]

  namespace :admin do
    get '/', to: 'static_pages#home'
    resources :users, only: [:index, :show, :destroy] do
      collection do
        get :search
      end
    end
    resources :quizzes do
      collection do
        get :all
        get :search
      end
      member do
        get :all_in_level
        get :all_in_section
        get :titles
        get :quizzes_in_title
      end
    end
    get '/quizzes/section_list/:id/:page', to: 'quizzes#get_section_list', as: 'quiz_sections'
    get '/quizzes/title_list/:id/:page', to: 'quizzes#get_title_list', as: 'quiz_titles'
    post 'category_with_experience_forms', to: 'quiz_categories#create'
    resources :quiz_categories do
      collection do
        get :levels
        get :new_level
        get :new_quiz
        get :search
      end
      member do
        get :new_category
        get :categories
        patch :sort
        get :edit_quiz
        get :new_quiz
      end
    end
    resources :articles do
      collection do
        get :search
        get :tag_search
        post :upload_image
        post :delete_image
      end
    end
    resources :communities do
      collection do
        get :search
        get :tag_search
      end
    end
    resources :talks, only: [:index, :show, :destroy] do
      collection do
        get :search
        get :comments
      end
    end
    resources :comments, only: [:index, :show, :destroy] do
      collection do
        get :search
      end
    end
    resources :announcements do
      collection do
        get :search
        get :tag_search
      end
    end
    resources :events do
      collection do
        get :search
        get :calendar
      end
    end
    resource :user, only: [:index, :destroy]
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
  }

  # deviseのroutesをカスタマイズで追加する
  devise_scope :user do
    get '/ranking', to: 'users#index', as: 'ranking'
    get 'user/:id', to: 'users#show', as: 'user'
    get '/user/:id/edit', to: 'users/registrations#edit', as: 'edit_profile'
  end

  # devise/~~~ をadmins/~~~に変える
  #   devise_for :admins, controllers: {
  #   sessions:      'admins/sessions',
  #   passwords:     'admins/passwords',
  #   registrations: 'admins/registrations'
  # }

  # routesをカスタマイズして、追加する
  # devise_for :admins, only: [:session] do
  # get '/admins/sign_in', :to => 'admins/sessions#new', :as => :new_admin_session
  # post 'admins/sign_in', :to =>'admins/sessions#create',:as => :admin_session
  # delete '/admins/', :to => 'admins/sessions#destroy', :as => :destroy_admin_session
  # end

  devise_for :admin, skip: :all
  devise_scope :admin do
    # loginリクエストに対してadmins/sessionsコントローラのnewアクションにルーティングし、new_user_session_pathと名付ける
    get '/admin/sign_in' => 'admin/sessions#new', as: 'new_admin_session'
    post '/admin/sign_in' => 'admin/sessions#create', as: 'admin_session'
    delete '/admin/sign_out' => 'admin/sessions#destroy', as: 'destroy_admin_session'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/talk.rb
class Talk < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :like_talks, dependent: :destroy
  has_many :users, through: :like_talks
  has_one_attached :img
  belongs_to :user
  counter_culture :user, column_name: 'talk_count'
  belongs_to :community
  counter_culture :community, column_name: 'talk_count'

  validates :content, :user_id, :community_id, presence: true
  validates :content, length: { maximum: 800 }
  validate :image_content_type, if: :was_attached?

  scope :in_joined_communities, -> (user) do
    includes(:user, [community: :community_users]).
      where(community_users: { user_id: user.id }).
      with_attached_img.
      sorted
  end

  scope :commented_top_3, -> { includes(:user).with_attached_img.order(likes_count: :desc).limit(3) }
  scope :liked_top_3, -> { with_attached_img.order(comments_count: :desc).limit(3) }
end

app/controllers/admin/talks_controller.rb
class Admin::TalksController < ApplicationController
  before_action :authenticate_admin!

  def index
    @q = Talk.includes([:user, :community]).ransack(params[:q])
    @talks = @q.result(distinct: true).paginate(params[:page], 15)
  end

  def show
    @talk = Talk.find(params[:id])
    @comments = @talk.comments
  end

  def destroy
    @talk = Talk.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to admin_talks_path }
      format.js { render :action => "destroy" }
    end
  end

  def search
    is_pagination?(params)
    if !params[:q]['community_name_or_user_name_or_content_cont_any'].nil?
      params[:q]['community_name_or_user_name_or_content_cont_any'] = params[:q]['community_name_or_user_name_or_content_cont_any'].split(/[ ]/)
      @keywords = Talk.includes([:user, :community]).ransack(params[:q])
      @talks = @keywords.result.paginate(params[:page], 15)
      @q = Talk.includes([:user, :community]).ransack(params[:q])
    else
      @q = Talk.includes([:user, :community]).ransack(params[:q])
      @talks = @q.result(distinct: true).paginate(params[:page], 15)
    end
    render template: 'admin/talks/index'
  end

  def comments
    @talk = Talk.find(params[:id])
    @comments = @talk.comments.paginate(params[:page], 15)
  end

  private

  def talk_params
    params.require(:talk).permit(:user_id, :community_id, :content, :img)
  end

  def is_pagination?(params)
    if params[:q]['user_name_or_content_cont_any'].is_a?(Array)
      params[:q]['user_name_or_content_cont_any'] = params[:q]['user_name_or_content_cont_any'].join(" ")
    end
  end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  before_action :only_login_user!
  before_action :get_unchecked_announce_count, :get_not_done_reviews_count
  before_action :set_ranked_talks, only: [:feed]
  before_action :which_page?, only: [:new, :edit, :create, :edit, :update]
  before_action :get_community_id, only: [:new, :edit, :create, :update]
  before_action :get_joined_communties

  def feed
    @talks = Talk.includes([:user, :community]).in_joined_communities(current_user)
    @comment = Comment.new
    @tags = Community.tags_on(:tags)
  end

  def new
    @talk = current_user.talks.new
  end

  def create
    @talk = current_user.talks.new(talk_params)
    if @talk.save
      redirect_to community_path(@talk.community)
    else
      render :new
    end
  end

  def show
  end

  def edit
    @talk = Talk.find(params[:id])
  end

  def update
    @talk = Talk.find(params[:id])
    if @talk.update(talk_params)
      @talk.img.purge if params[:talk][:delete_img].present?
      redirect_to community_path(@talk.community, anchor: "talk_#{@talk.id}")
    else
      @community = @talk.community
      render :edit
    end
  end

  def destroy
    @talk = Talk.find(params[:id])
    @talk.destroy
  end

  private

  def talk_params
    params.require(:talk).permit(:user_id, :community_id, :content, :img)
  end

  def authenticate_edit_delete
    unless user_signed_in?
      render :index
      flash.now[:notice] = "you don't have right to delete...."
    end
  end

  def get_community_id
    if params[:community_page?].present?
      @community = Community.find(params[:community_page?])
    else
      @communities = current_user.communities
    end
  end

  def which_page?
    if params[:community_page?].present?
      @community_page = Community.find(params[:community_page?]).id
    else
      @community_page = nil
    end
  end

  def set_ranked_talks
    @commented_top_3 = Talk.commented_top_3
    @liked_top_3 = Talk.liked_top_3
  end

  def get_joined_communties
    @joined_communities = current_user.communities
  end
end

app/views/talks/_action_btns.html.erb
<ul class="talk_btns">
  <li id="comment_btn_<%= talk.id %>" class="comment_btn">
    <%= link_to comments_path(id: talk.id), remote: true do %>
      <%= icon("fas", "comment-alt") %>  <%= talk.comments_count %>  <%= talk.comments_count > 1 ? "Comments" : "Comment" %>
    <% end %>
  </li>
  <li id="like_btn_<%= talk.id %>">
    <% if own_post?(talk) %>
        <span class="like_btn"><%= icon("fas", "heart") %> <%= talk.likes_count %></span>
    <% else %>
      <% if current_user.already_liked_talk?(talk) %>
        <%= link_to like_talk_path(talk), class:"like_btn" ,remote: true, method: :delete do %>
          <%= icon("fas", "heart") %> <%= talk.likes_count %>
        <% end %>
      <% else %>
        <%= link_to like_talks_path(id: talk.id), class:"like_btn" ,remote: true, method: :post do %>
          <%= icon("far", "heart") %> <%= talk.likes_count %>
        <% end %>
      <% end %>
    <% end %>
  </li>
  <% if own_post?(talk) %>
    <li>
      <% if community_page? %>
        <%= link_to edit_talk_path(talk, community_page?: @community.id), class: "edit_btn" do %>
          <%= icon("fas", "edit") %> Edit
        <% end %>
      <% else %>
        <%= link_to edit_talk_path(talk, community_page?: nil), class: "edit_btn" do %>
          <%= icon("fas", "edit") %> Edit
        <% end %>
      <% end %>
    </li>
    <li>
      <%= link_to talk_path(talk), class: "delete_btn", data: { confirm: 'Delete this post?' }, method: :delete, remote: true do %>
        <%= icon("fas", "trash-alt") %> Delete
      <% end %>
    </li>
  <% end %>
</ul>

app/views/talks/_breadcrumbs.html.erb
<p class="breadcrumbs">
  <%= icon("fas","map-marker-alt") %> 
  <%= link_to "Home", root_path %> >  
  <%= link_to "Communities", communities_path %> >
  <%= link_to "#{@community.name}", community_path(@community) %> >
  <%= action %>
</p>

app/views/talks/_form.html.erb
<%= form_with model: talk, local: true, builder: CustomFormBuilder do |f| %>
  <%= hidden_field_tag :community_page?, @community_page %>
  <div class="field">
    <% if @community_page.present? %>
      <%= f.hidden_field :community_id, value: @community.id %>
    <% else %>
      <%= f.label :community_id %>
      <%= f.select :community_id, @communities.map{|c| [c.name, c.id] } %>
    <% end %>
  </div>
  <div class="field input_content">
    <%= f.label :content %><br>
    <%= f.text_area :content, class: "content_input" %>
  </div>
  <%= render 'upload_img', model: talk, f: f %>
  <div class="actions">
    <%= f.submit action %>
  </div>
<% end %>
<%= javascript_include_tag "prev_img.js" %>

app/views/talks/_info_of_poster.html.erb
<ul class="talk_info">
  <li class="inline">
    <%= link_to "#{talk.community.name}", community_path(talk.community_id) %>
  </li>
  <li class="posted_time inline">
    Posted by <%= link_to talk.user.name, user_path(talk.user) %> 
  </li>
  <li class="inline"><%= time_ago_in_words(talk.created_at) %> ago</li>
</ul>

app/views/talks/_like_btn.html.erb
<% if own_post?(talk) %>
    <%= icon("fas", "heart") %> <%= talk.likes_count %>
<% else %>
  <% if current_user.already_liked_talk?(talk) %>
    <%= link_to like_talk_path(talk), class:"like_btn" ,remote: true, method: :delete do %>
      <%= icon("fas", "heart") %> <%= talk.likes_count %>
    <% end %>
  <% else %>
    <%= link_to like_talks_path(id: talk.id), class:"like_btn" ,remote: true, method: :post do %>
      <%= icon("far", "heart") %> <%= talk.likes_count %>
    <% end %>
  <% end %>
<% end %>

app/views/talks/_side_section.html.erb
<div class="side_section talk_page pc">
  <div class="side_content">
    <h4><%= icon("fas", "tags") %> Menu (メニュー)</h4>
    <div class="side_inner_box">
      <div>
        <%= link_to "Create talk", new_talk_path(from_feed: "true"), class: "block center create_talk_btn" %>
        <%= link_to "create community" ,new_community_path, class: "block center create_community_btn" %>
      </div>
    </div>
  </div>
  <%= render 'talks/top_3_talks' %>
  <%= render 'communities/joined_communities' %>
</div>

app/views/talks/_talk.html.erb
<div class="talk_wrapper" id="talk_<%= talk.id %>">
  <%= render 'talks/info_of_poster', talk: talk %>
  <div class="talk_content_wrapper">
    <%= simple_format(text_url_to_link(h(talk.content)).html_safe, class: 'talk_content') %>
    <p class="center"><%= image_tag talk.img if talk.img.attached? %></p>
  </div>
  <%= render 'talks/action_btns', talk: talk %>
  <div id="comments_wrapper_<%= talk.id%>" class="hidden comments_wrapper">
    <%= render 'comments/form', comment: @comment, talk: talk %>
    <div id="comments_of_talk<%= talk.id %>">
    </div>
    <div id="view_more_<%= talk.id %>" class="center view_more"></div>
  </div>
</div>

app/views/talks/_top_3_talks.html.erb
<div class="side_content">
  <h4><%= icon("fas", "comment-alt") %> Most Commented</h4>
  <div class="top_3_talk_wrapper">
    <% if @commented_top_3.present? %>
      <%= render partial: "ranked_talk", collection: @commented_top_3, as: :talk %>
    <% else %>
      <p>No Data</p>
    <% end %>
  </div>
</div>
<div class="side_content">
  <h4><%= icon("fas", "heart") %> Most Liked</h4>
  <div class="top_3_talk_wrapper">
    <% if @liked_top_3.present? %>
      <%= render partial: "ranked_talk", collection: @liked_top_3, as: :talk %>
    <% else %>
      <p>No Data</p>
    <% end %>
  </div>
</div>

app/views/talks/_top_create_talk_btn.html.erb
<div id="top_create_talk_btn">
  <% if community_page? %>
    <%= link_to new_talk_path(talk: { from_community_page: community.id }) do %>
      <%= icon("fas","pen") %>
    <% end %>
  <% else %>
    <%= link_to new_talk_path(talk: { from_talk_page: true }) do %>
      <%= icon("fas","pen") %>
    <% end %>
  <% end %>
</div>

app/views/talks/edit.html.erb
<% content_for(:html_title) { "Edit Talk " } %>
<% if @community_page %>
  <%= render 'breadcrumbs', action: "Edit" %>
<% else %>
  <% breadcrumb :edit_talk, @talk %>
<% end %>
<p class="form_title">Edit Talk</p>
<div class="form_wrapper">
  <%= render partial: 'form', locals: { talk: @talk, communities: @communities, action: 'Update' } %>
</div>
<div class="hidden user_menu_section">
  <%= render 'user_menu_in_mobile' %>
</div>
<div class="user_menu_section talk_page hidden">
  <%= render 'side_section' %>
</div>

app/views/talks/index.html.erb
<% content_for(:html_title) { "Talks Index" } %>
<% breadcrumb :talks, @talks %>
<div class="section_wrapper">
  <div class="main_section inline" id="talk_index">
    <h1 class="center bold page_title">Talks index</h1>
    <div class="talk_index jscroll">
      <% if @talks.present? %>
        <%= render partial: 'talk', collection: @talks, as: :talk %>
      <% else %>
        <p class="center">No...talk</p>
      <% end %>
    </div> 
    <div id="to_top_btn_wrapper">
      <a href="#" id="talk_top_btn"><%= icon("fas", "arrow-circle-up") %></a>
    </div>
  </div>
  <div class="side_section talk_page">
      <%= render 'side_section' %>
  </div>
</div>

app/views/talks/new.html.erb
<% content_for(:html_title) { "Create Talk " } %>
<% if @community_page %>
  <%= render 'breadcrumbs', action: "New" %>
<% else %>
  <% breadcrumb :new_talk, @talk %>
<% end %>
<p class="form_title">Create Talk</p>
<div class="form_wrapper">
  <%= render partial: 'form', locals: { talk: @talk, communities: @communities, action: 'Post' } %>
</div>
<div class="hidden user_menu_section">
  <%= render 'user_menu_in_mobile' %>
</div>
<div class="user_menu_section talk_page hidden">
  <%= render 'side_section' %>
</div>

app/views/talks/show.html.erb
<div class="talk_container">
    <%= render partial: 'talk', locals: {talk: @talk} %>
  <div id="comment_form">
    <%= render partial: 'comments/comments_form' %>
  </div>
  <div id="comments_index" class="comment_container jscroll scroll_list" >
    <%= render partial: 'comments/comments' %>
  </div>
</div>

app/views/talks/update.js.erb
$("#talk_<%= @talk.id %>").replaceWith("<%= j(render partial: 'talk', locals: { talk: @talk }) %>");
$('#modalArea').fadeOut();