config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  resources :quiz_categories, only: [:index, :show]
  get '/quizzes/:id/play', to: 'quizzes#play', as: 'quiz_play'
  get '/quizzes/:id/play_mistakes', to: 'quizzes#play_mistakes', as: 'play_mistakes'
  resources :mistakes, only: [:index, :destroy] do
    collection do
      get :search
    end
  end
  resources :score_records, only: [:index, :show, :create]
  resources :talks, except: [:show] do
    collection do
      get :sort
      get :search
      get :tag_search
      get :feed
    end
    member do
      get :user
    end
  end
  resources :like_talks, only: [:create, :destroy]
  resources :comments
  resources :articles, only: [:show, :index] do
    collection do
      get :sort
      get :search
      get :tag_search
    end
  end
  resources :like_articles, only: [:create, :destroy]
  resources :bookmarks, only: [:index, :create, :destroy]
  resources :communities do
    collection do
      get :sort
      get :search
      get :tag_search
      get :joined
    end
    member do
      get :join
      get :leave
    end
  end
  resources :community_users, only: [:create, :destroy]
  resources :announcements, only: [:index, :show]
  resources :events, only: [:index, :show]
  resources :reviews, only: [:index, :destroy]

  namespace :admin do
    get '/', to: 'static_pages#home'
    resources :users, only: [:index, :show, :destroy] do
      collection do
        get :search
      end
    end
    resources :quizzes do
      collection do
        get :all
        get :search
      end
      member do
        get :all_in_level
        get :all_in_section
        get :titles
        get :quizzes_in_title
      end
    end
    get '/quizzes/section_list/:id/:page', to: 'quizzes#get_section_list', as: 'quiz_sections'
    get '/quizzes/title_list/:id/:page', to: 'quizzes#get_title_list', as: 'quiz_titles'
    post 'category_with_experience_forms', to: 'quiz_categories#create'
    resources :quiz_categories do
      collection do
        get :levels
        get :new_level
        get :new_quiz
        get :search
      end
      member do
        get :new_category
        get :categories
        patch :sort
        get :edit_quiz
        get :new_quiz
      end
    end
    resources :articles do
      collection do
        get :search
        get :tag_search
        post :upload_image
        post :delete_image
      end
    end
    resources :communities do
      collection do
        get :search
        get :tag_search
      end
    end
    resources :talks, only: [:index, :show, :destroy] do
      collection do
        get :search
        get :comments
      end
    end
    resources :comments, only: [:index, :show, :destroy] do
      collection do
        get :search
      end
    end
    resources :announcements do
      collection do
        get :search
        get :tag_search
      end
    end
    resources :events do
      collection do
        get :search
        get :calendar
      end
    end
    resource :user, only: [:index, :destroy]
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
  }

  # deviseのroutesをカスタマイズで追加する
  devise_scope :user do
    get '/ranking', to: 'users#index', as: 'ranking'
    get 'user/:id', to: 'users#show', as: 'user'
    get '/user/:id/edit', to: 'users/registrations#edit', as: 'edit_profile'
  end

  # devise/~~~ をadmins/~~~に変える
  #   devise_for :admins, controllers: {
  #   sessions:      'admins/sessions',
  #   passwords:     'admins/passwords',
  #   registrations: 'admins/registrations'
  # }

  # routesをカスタマイズして、追加する
  # devise_for :admins, only: [:session] do
  # get '/admins/sign_in', :to => 'admins/sessions#new', :as => :new_admin_session
  # post 'admins/sign_in', :to =>'admins/sessions#create',:as => :admin_session
  # delete '/admins/', :to => 'admins/sessions#destroy', :as => :destroy_admin_session
  # end

  devise_for :admin, skip: :all
  devise_scope :admin do
    # loginリクエストに対してadmins/sessionsコントローラのnewアクションにルーティングし、new_user_session_pathと名付ける
    get '/admin/sign_in' => 'admin/sessions#new', as: 'new_admin_session'
    post '/admin/sign_in' => 'admin/sessions#create', as: 'admin_session'
    delete '/admin/sign_out' => 'admin/sessions#destroy', as: 'destroy_admin_session'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/quiz_category.rb
class QuizCategory < ApplicationRecord
  acts_as_list scope: :parent_id
  acts_as_nested_set
  has_many :quizzes, foreign_key: "category_id", dependent: :destroy
  has_many :categories, -> { order(position: :asc) }, foreign_key: 'parent_id', class_name: 'QuizCategory'
  has_many :mistakes, foreign_key: "title_id"
  has_many :learning_levels, foreign_key: "title_id", dependent: :destroy
  has_many :reviews, foreign_key: "title_id", dependent: :destroy
  has_many :masters, foreign_key: "title_id", dependent: :destroy
  has_many :users, through: :master
  has_one :quiz_experience, foreign_key: 'title_id', dependent: :destroy
  belongs_to :parent, foreign_key: "parent_id", optional: true

  validates :name, presence: true
  scope :levels, -> { where(depth: 0).order(position: :asc) }
  scope :sections_in, ->(level) { level.children }
  scope :titles_in, ->(section) { section.children }
  scope :ancestors_of, ->(node) do
    left_condition = arel_table[left_column_name].lt(node.left)
    right_condition = arel_table[right_column_name].gt(node.right)
    where(left_condition).where(right_condition)
  end

  def is_level?
    root?
  end

  def is_section?
    true if depth == 1
  end

  def is_title?
    true if depth == 2
  end

  def get_ancestors
    unless root?
      ancestors
    end
  end

  def get_desendants
    if root
      descendants
    end
  end

  def masterd?
    learning_levels.where(user_id: current_user.id)
  end
end

app/controllers/admin/quiz_categories_controller.rb
class Admin::QuizCategoriesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @categories = QuizCategory.levels
  end

  def categories
    @parent = QuizCategory.find(params[:id])
    @ancestors = @parent.get_ancestors
    get_children_category(@parent)
    if @parent.is_title?
      @quizzes = @parent.quizzes
    end
    render 'index'
  end

  def new_level
    @category = QuizCategory.new
    render "new_level"
  end

  def new_category
    @parent = QuizCategory.find(params[:id])
    @category = @parent.is_section? ? CategoryWithExperienceForm.new : QuizCategory.new
    render "new_category"
  end

  def new_quiz
    @category = QuizCategory.find(params[:id])
    @quiz = Quiz.new
  end

  def create
    @category = title_form?(params) ? CategoryWithExperienceForm.new(category_with_experience_params) : QuizCategory.new(category_params)
    if @category.save
      set_categories(@category)
      flash.now[:notice] = "新しいカテゴリーを作成しました！"
      render "create"
    else
      rendering(@category)
    end
  end

  def edit
    @category = QuizCategory.find(params[:id])
  end

  def edit_quiz
    @quiz = Quiz.find(params[:id])
  end

  def update
    @category = QuizCategory.find(params[:id])
    if @category.is_title?
      @category = CategoryWithExperienceForm.new(category_params)
      @category.update(category_params)
    else
      @category.update(category_params)
      if @category.save
        flash.now[:notice] = "カテゴリーを編集しました。"
      else
        render :edit
      end
    end
  end

  def destroy
    @category = QuizCategory.find(params[:id]).destroy
  end

  def sort
    if params[:id] == "undefined"
      category = QuizCategory.levels[params[:from].to_i]
      category.insert_at(params[:to].to_i + 1)
    else
      @category = QuizCategory.find(params[:id])
      child = @category.categories[params[:from].to_i]
      child.insert_at(params[:to].to_i + 1)
    end
  end

  private

  def category_params
    params.require(:quiz_category).permit(:name, :parent_id, :rate, :id)
  end

  def category_with_experience_params
    params.require(:category_with_experience_form).permit(:name, :parent_id, :rate)
  end

  def get_children_category(category)
    if category.is_title?
      @quizzes = category.quizzes
    else
      @categories = category.categories
    end
  end

  def rendering(category)
    if category.parent_id
      @parent = QuizCategory.find(category.parent_id)
      render "new_category"
    else
      render "new_level"
    end
  end

  def set_categories(category)
    if category.parent_id
      @parent = QuizCategory.find(category.parent_id)
      @categories = @parent.children
    else
      @categories = QuizCategory.where(depth: 0)
    end
  end

  def title_form?(params)
    params[:category_with_experience_form].present? ? true : false
  end

  def is_pagination?(params)
    if params[:q]['name_or_introduction_or_users_name_cont_any'].is_a?(Array)
      params[:q]['name_or_introduction_or_users_name_cont_any'] = params[:q]['name_or_introduction_or_users_name_cont_any'].join(" ")
    end
  end
end

app/controllers/quiz_categories_controller.rb
class QuizCategoriesController < ApplicationController
  before_action :only_login_user!
  before_action :get_unchecked_announce_count, :get_not_done_reviews_count

  def index
    @levels = QuizCategory.levels
  end

  def show
    @level = QuizCategory.find(params[:id])
    @sections = @level.children.includes(:learning_levels, [categories: :quizzes])
  end
end

app/helpers/quiz_categories_helper.rb
module QuizCategoriesHelper
  def experience_array
    (0..25).map { |num| (1 + (num.to_d * 0.1)).floor(2) }
  end

  def form_title(parent)
    if parent.is_level?
      "Section 名"
    elsif parent.is_section?
      "Title 名"
    end
  end

  def get_category(category)
    if category.is_level?
      "Level 名"
    elsif category.is_section?
      "Section 名"
    elsif category.is_title?
      "Title 名"
    end
  end

  def title_index?(category)
    category.present? && category.is_title?
  end

  def get_learning_level(user, category)
    if learning_level = category.learning_levels.where(user_id: user.id).first
      learning_level.percentage
    end
  end

  def bar_color(user, category)
    case get_learning_level(user, category)
    when 0..29
      "red_bg"
    when 30..49
      "yellow_bg"
    when 50..79
      "blue_bg"
    when 80..99
      "green_bg"
    when 100
      "gold_bg"
    end
  end
end

app/views/admin/quiz_categories/_breadcrumbs.html.erb
<ul class="breadcrumbs_list">
  <li><%= icon("fas","map-marker-alt") %> <%= link_to "Home", root_path %> ＞ <li>
  <li><%= link_to "クイズカテゴリー TOP", admin_quiz_categories_path %></li>
  <% if defined?(@parent) %>
    <% unless @parent.is_level? %>
      <% @ancestors.each do |ancestor| %>
        <li>＞ <%= link_to ancestor.name, categories_admin_quiz_category_path(ancestor) %></li>
      <% end %>
    <% end %>
    <li>＞ <%= @parent.name %></li>
  <% end %>
</ul>

app/views/admin/quiz_categories/_category_info.html.erb
<p class="parent_name center">
  <span id="category_name"><%= parent.name %></span>
  <%= link_to "編集", edit_admin_quiz_category_path(parent), remote: true, id: "category_edit_btn" %>
</p>
<% if parent.is_title? %>
  <p class="center" >経験値 <span id ="quiz_experience"><%= parent.quiz_experience.rate %></span></p>
<% end %>

app/views/admin/quiz_categories/_create_btn.html.erb
<% if title_index?(parent) %>
  <%= link_to 'NEW', new_quiz_admin_quiz_category_path(parent), class: 'admin_create_btn', remote: true %>
  <span class="scroll_x">※ 横スクロール可</span>
<% elsif @parent.present? %>
  <%= link_to 'NEW', new_category_admin_quiz_category_path(parent), class: 'admin_create_btn', remote: true %>
  <span><%= "※ ドラッグ＆ドロップで並び替え" unless title_index?(parent) %></span>
<% else %>
  <%= link_to 'NEW', new_level_admin_quiz_categories_path, class: 'admin_create_btn', remote: true %>
  <span><%= "※ ドラッグ＆ドロップで並び替え" unless title_index?(parent) %></span>
<% end %>

app/views/admin/quiz_categories/_create_quiz_category_btn.html.erb
<p class="category_new">
  <span><%= "※ ドラッグ＆ドロップで並び替え" unless title_page?(parent) %></span>
  <% if title_page?(parent) %>
    <%= link_to '新規作成', new_quiz_admin_quiz_category_path(parent), class: 'new_btn', remote: true %>
  <% elsif section_page?(parent) %>
    <%= link_to '新規作成', new_category_admin_quiz_category_path(parent), class: 'new_btn', remote: true %>
  <% else %>
    <%= link_to '新規作成', new_level_admin_quiz_categories_path, class: 'new_btn', remote: true %>
  <% end %>
</p>

app/views/admin/quiz_categories/_edit_form.html.erb
<div class="form_wrapper">
  <p class="center bold">Category Form</p>
  <%= form_with model: [:admin, category], builder: CustomFormBuilder do |f| %>
    <%= f.hidden_field :id, value: category.id %>
    <div class="field" >
      <p class="bold"><%= get_category(category) %></p>
      <%= f.text_field :name , id: 'form_input' %>
    </div>
    <% if category.is_title? %>
      <div class="field" >
        <p class="bold">経験値</p>
        <%= f.select :rate, experience_array, id: 'form_input', selected: category.quiz_experience.rate %>
      </div>
    <% end %>
    <div class="form_btn">
      <%= f.submit '編集',id: 'form_btn'%>
    </div>
    <% if defined?(parent) %>
      <%= f.hidden_field :parent_id, value: parent.id %>
    <% end %>
  <% end %>
</div>

app/views/admin/quiz_categories/_form.html.erb
<div class="form_wrapper">
  <p class="center bold">Category Form</p>
  <p class="error_message"><%= "入力値が正しくありません。" if category.errors.any? %></p>
  <%= form_with model: [:admin, category], builder: CustomFormBuilder do |f| %>
    <div class="field" >
      <p class="bold"><%= defined?(parent) ? form_title(parent) : "Level 名" %></p>
      <%= f.text_field :name ,id: 'form_input' %>
    </div>
      <% if defined?(parent) && parent.is_section? %>
        <div class="field" >
          <p class="bold">経験値</p>
          <%= f.select :rate, experience_array, id: 'form_input' %>
        </div>
      <% end %>
    <div class="form_btn">
      <%= f.submit '作成',id: 'form_btn'%>
    </div>
    <% if defined?(parent) %>
      <%= f.hidden_field :parent_id, value: parent.id %>
    <% end %>
  <% end %>
</div>

app/views/admin/quiz_categories/_levels_list.html.erb
<%= render partial: 'quiz_category', collection: categories, as: :category %>

app/views/admin/quiz_categories/_quiz_columns.html.erb
<thead>
  <tr class="index_head center">
    <th>No</th>
    <th>Question</th>
    <th>Answer</th>
    <th>C2</th>
    <th>C3</th>
    <th>C4</th>
    <th class="date_column">Creation Data</th>
    <th class="date_column">Update Date</th>
    <th class="action_column notes">※ソート可（カラム名クリック）</th>
  </tr>
</thead>

app/views/admin/quiz_categories/_quiz_form.html.erb
<div class="form_wrapper">
  <%= form_with model: [:admin, quiz], builder: CustomFormBuilder do |f| %>
    <% if category.present? %>
      <%= f.hidden_field :category_id, value: category.id %>
    <% end %>
    <div class="field">
      <%= f.label :question %>
      <%= f.text_field :question %>
    </div>
    <div class="field">
      <%= f.label :choice1 %>
      <%= f.text_field :choice1 %>
    </div>
    <div class="field">
      <%= f.label :choice2%>
      <%= f.text_field :choice2 %>
    </div>
    <div class="field">
      <%= f.label :choice3 %>
      <%= f.text_field :choice3 %>
    </div>
    <div class="field">
      <%= f.label :choice4 %>
      <%= f.text_field :choice4 %>
    </div>
    <div class="form_btn">
      <%= f.submit "作成", id: 'form_btn',data: { confirm: "送信しますか？"} %>
    </div>
  <% end %>
</div>

app/views/admin/quiz_categories/edit_quiz.js.erb
$("#modal").html("<%= j(render partial: 'admin/quizzes/form', locals: { quiz: @quiz, category: @category, action: "編集" }) %>");
$('#modalArea').fadeIn();

app/views/admin/quiz_categories/index.html.erb
<% content_for(:html_title) { "Quiz Category Index" } %>
<%= render 'breadcrumbs' %>
<div class="quiz_categories">
  <div class="quiz_category_parent">
    <% unless @parent %>
      <p class="parent_name center"><%= icon("fas","mp-marker-alt") %> Quiz カテゴリー</p>
    <% else %>
      <%= render partial: 'category_info', locals: { parent: @parent, ancestors: @ancestors } %>
    <% end %>
  </div>
  <div class="category_children">
    <p class="create_btn_wrapper">
      <%= render 'create_btn', parent: @parent %>
    </p>
    <% if title_index?(@parent) %>
      <div class="table_wrapper">
        <table class="index_table" >
          <%= render 'quiz_columns' %>
          <tbody id ="quizzes_index">
            <%= render partial: 'admin/quizzes/quiz', collection: @quizzes, as: :quiz %>
          </tbody>
        </table>
    <% else %>
        <ul id="sortable_list" class="quiz_category_list quizzes_list">
          <%= render partial: 'admin/quiz_categories/category', collection: @categories, as: :category %>
        </ul>
        <%= hidden_field_tag :parent_id, @parent.id if @parent.present? %>
    <% end %>
    </div>
  </div>
</div>

app/views/admin/quiz_categories/new_category.js.erb
$("#modal").html("<%= j(render partial: 'form', locals: { category: @category, parent: @parent }) %>");
$('#modalArea').fadeIn();

app/views/admin/quiz_categories/new_quiz.js.erb
$("#modal").html("<%= j(render partial: 'admin/quizzes/form_in_category_page', locals: { quiz: @quiz, category: @category }) %>");
$('#modalArea').fadeIn();

app/views/admin/quiz_categories/show.js.erb
$(".quizzes_list").html("<%= j(render partial: 'admin/quizzes/quiz', collection: @quizzes, as: :quiz) %>");
$('#modalArea').fadeOut();
if(flash){
$("#flash_wrapper").html("<%= j(render 'layouts/flash') %>");
setTimeout("$('#flash').fadeOut('slow')",2000);
}